# SPDX-FileCopyrightText: 2025 RAprogramm
# SPDX-License-Identifier: MIT

name: Format

on:
  workflow_call:
    inputs:
      rust_changed:
        required: true
        type: string

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    if: inputs.rust_changed == 'true'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de # master
        with:
          toolchain: nightly
          components: rustfmt
      - run: cargo +nightly fmt --all -- --check
