# SPDX-FileCopyrightText: 2025 RAprogramm
# SPDX-License-Identifier: MIT

name: Unused Dependencies

on:
  workflow_call:
    inputs:
      deps_changed:
        required: true
        type: string

jobs:
  machete:
    name: Unused Dependencies
    runs-on: ubuntu-latest
    if: inputs.deps_changed == 'true'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@2c7215f132e9ebf062739d9130488b56d53c060c # master
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          key: machete
      - uses: taiki-e/install-action@07b4745e0c39a41822af610387492e3e53aa222b # v2.83.4
        with:
          tool: cargo-machete
      - name: Check for unused dependencies
        run: cargo machete
