# SPDX-FileCopyrightText: 2025 RAprogramm
# SPDX-License-Identifier: MIT

name: Publish to crates.io

on:
  workflow_call:
    inputs:
      new_tag:
        required: true
        type: string
    secrets:
      CRATES_IO_TOKEN:
        required: true

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2
      - name: Publish
        run: |
          output=$(cargo publish --token ${{ secrets.CRATES_IO_TOKEN }} --allow-dirty 2>&1) || {
            if echo "$output" | grep -q "already exists"; then
              echo "::notice::Version already published to crates.io"
              exit 0
            else
              echo "$output"
              exit 1
            fi
          }
