# SPDX-FileCopyrightText: 2025 RAprogramm
# SPDX-License-Identifier: MIT

name: Semver Check

on:
  workflow_call:
    inputs:
      rust_changed:
        required: true
        type: string

jobs:
  semver:
    name: Semver Check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && inputs.rust_changed == 'true'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@2c7215f132e9ebf062739d9130488b56d53c060c # master
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          key: semver
      - uses: taiki-e/install-action@07b4745e0c39a41822af610387492e3e53aa222b # v2.83.4
        with:
          tool: cargo-semver-checks
      - name: Check semver compatibility
        run: cargo semver-checks check-release --default-features
