# SPDX-FileCopyrightText: 2025 RAprogramm
# SPDX-License-Identifier: MIT

name: Semver Check

on:
  workflow_call:
    inputs:
      rust_changed:
        required: true
        type: string

jobs:
  semver:
    name: Semver Check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && inputs.rust_changed == 'true'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de # master
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2
        with:
          key: semver
      - uses: taiki-e/install-action@4076c08d76dba979c11a7285295b0716c1d67908 # v2.87.15
        with:
          tool: cargo-semver-checks
      - name: Check semver compatibility
        run: cargo semver-checks check-release --default-features
